apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trek

resources:
- namespace.yaml
- external-secrets.yaml
- storage-config.yaml
- ingressroute.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: trek
  path: storage-config.patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: trek
  path: places-key.patch.yaml

helmCharts:
- name: trek
  repo: https://chart.liketrek.com
  releaseName: trek
  includeCRDs: true
  version: 4.1.1
  namespace: trek
  valuesFile: values.yaml
