---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/fomiller/homelab/authentik-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-ses-smtp
  namespace: authentik
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: authentik-ses-smtp
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/fomiller/homelab/authentik-ses-smtp
