apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ingressroute.yaml
- redpanda-cluster.yaml

namespace: redpanda

helmCharts:
- name: operator
  repo: https://charts.redpanda.com
  releaseName: redpanda-operator
  includeCRDs: true
  version: 26.1.8
  namespace: redpanda
  valuesFile: operator-values.yaml
