output "tunnel_id" {
  value = cloudflare_zero_trust_tunnel_cloudflared.this.id
}

output "tunnel_cname_target" {
  value = "${cloudflare_zero_trust_tunnel_cloudflared.this.id}.cfargotunnel.com"
}

# Consumed by aws/global/secrets (archived to Secrets Manager for the
# cloudflared pods) — generated by Cloudflare from the tunnel above, not by
# this unit, so it can't be produced any other way than reading it back.
output "tunnel_token" {
  value     = data.cloudflare_zero_trust_tunnel_cloudflared_token.this.token
  sensitive = true
}
