---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: subnet-router
spec:
  hostname: k8s-subnet-router
  tags:
    - "tag:k8s"
  subnetRouter:
    advertiseRoutes:
      - "192.168.0.0/24"
