# .github/workflows/deploy-cloudflare.yaml

name: 'Terragrunt Deploy - Cloudflare'

on:
  push:
    paths:
      - '.github/workflows/deploy-cloudflare.yaml'
      - 'infra/modules/cloudflare/**'
      - 'justfile'

jobs:
  Pre-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'

  Deploy-infra:
    name: 'Deploy Cloudflare Infra'
    needs: Pre-check
    uses: fomiller/gh-actions/.github/workflows/terragrunt.yaml@main
    with:
      environment: dev
      infra-dir: infra/modules/cloudflare
      doppler-project: homelab
    secrets: inherit
