# .github/workflows/deploy-talos.yaml

name: 'Terragrunt Deploy - Talos'

on:
  push:
    paths:
      - '.github/workflows/deploy-talos.yaml'
      - 'infra/modules/talos/**'
      - 'justfile'

jobs:
  Pre-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'

  Deploy-infra:
    name: 'Deploy Talos Infra'
    needs: Pre-check
    uses: fomiller/gh-actions/.github/workflows/terragrunt.yaml@main
    with:
      environment: dev
      infra-dir: infra/modules/talos
      doppler-project: homelab
      use-tailscale: true
      tailscale-tags: tag:ci
    secrets: inherit

    # use if you need to debug workflow
    # - name: DEBUG
    #   uses: lhotari/action-upterm@v1
    #   with:
    #       limit-access-to-actor: true
    #       limit-access-to-users: Fomiller
